[package]
name = "icarus-math"
version = "0.1.0"
edition = "2021"

[dependencies]
num-complex = { workspace = true }
num-traits = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
